version: '3'

services:
  database:
    image: postgres
    restart: always
    ports:
      - ${DATASOURCE_PORT}:${DATASOURCE_PORT}
    environment:
      - POSTGRES_PASSWORD=${DATASOURCE_PASSWORD}
      - POSTGRES_USER=admin
